name: google_generative_ai
description: >-
  The Google Generative AI SDK for Dart - allows access to state-of-the-art
  LLMs.
repository: https://github.com/google/generative-ai-dart/tree/main/pkgs/google_generative_ai

publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  crypt: ^4.3.0
  http: ^1.1.0
  pool: ^1.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
